## Read Cross Validation Results

In [1]:
import numpy as np 
import pandas as pd
import altair as alt
from os import listdir
from os.path import isfile, join
from utils.util import read_results, read_eval_result

alt.data_transformers.disable_max_rows()
pd.set_option('display.max_rows', 500)

In [2]:
#read the cross validation results
#mypath = "outputs/crossval"
mypath = "outputs/repeatedcrossval"
files = [f for f in listdir(mypath) if isfile(join(mypath, f))]

final_df = pd.DataFrame()

for file in files:
    if file.endswith('.xlsx'):
        filename = join(mypath,file)
        df = read_results(filename)
        final_df = pd.concat([final_df,df])

#filter model 
final_df = final_df[final_df['model'].isin(['SVM','RandomForest','LogisticRegression','NaiveBayes','DecisionTree'])]

#numbering the evaluation metrics as each metric has as many values as the number of n_fold cross validation (n=5)
eval_metrics = ['Accuracy','MCC','F_1','F_beta_0.5','F_beta_2','Precision','Recall']

for metric in eval_metrics:
    score_columns = final_df.filter(regex=metric).columns
    final_df['mean_{}'.format(metric)] = final_df[score_columns].mean(axis=1)
    final_df['std_{}'.format(metric)] = final_df[score_columns].std(axis=1)
    final_df['{}'.format(metric)] = final_df.apply(lambda x: '{:.3f}±{:.3f}'.format(x['mean_{}'.format(metric)],x['std_{}'.format(metric)]), axis=1)

#final_df = final_df[final_df['fold']=='StratifiedGroupKFold']
final_df.rename(columns={'mean_F_1':'mean_F1','F_1':'F1'}, inplace=True)

In [3]:
#rank the RCKmer and Kmer based on F1 score per dataset
kmer_family = final_df[(final_df.representation.str.startswith('Kmer'))].copy()
kmer_family['group_rank'] = kmer_family.groupby(['dataset','fold'])['mean_F1'].rank(method="first", ascending=False)

rckmer_family = final_df[(final_df.representation.str.startswith('RCKmer'))].copy()
rckmer_family['group_rank'] = rckmer_family.groupby(['dataset','fold'])['mean_F1'].rank(method="first", ascending=False)

kmer_table = pd.concat([kmer_family,rckmer_family])

In [4]:
#assign the rank of RCKmer and Kmer to the original table
df_merged = pd.merge(final_df, kmer_table[['dataset','representation','fold','group_rank']], on=['dataset','representation','fold'], how='left')
df_merged = df_merged.fillna(0.0)

In [5]:
#select the best RCKmer and Kmer only
sub_final_df = df_merged[df_merged['group_rank']<=1.0].copy()
sub_final_df['rank'] = sub_final_df.groupby(['dataset','representation','fold'])['mean_F1'].rank(method="first", ascending=False)
sub_final_df = sub_final_df[sub_final_df['rank']==1]

#show the top 5 performing representations along with the corresponding model sorted by F_1 score in descending order
sub_df_stratified_group_top_n = sub_final_df.groupby('dataset').apply(pd.DataFrame.nlargest, n=5, columns=['mean_F1'])
sub_df_stratified_group_top_n[['model','representation','F1','F_beta_0.5','F_beta_2','MCC','Accuracy','Precision','Recall']]#,'data_split_1', 'data_split_2','data_split_3','data_split_4','data_split_5' ]]

                                model  representation           F1  \
dataset
benbow       1049                 SVM        RCKmer-7  0.928±0.023
             1014                 SVM          Kmer-7  0.909±0.026
             1143                 SVM   Z_curve_48bit  0.880±0.039
             350         RandomForest          PseKNC  0.878±0.037
             1141                 SVM  Z_curve_144bit  0.874±0.030
gicluster    2284                 SVM          Kmer-6  0.627±0.136
             2324                 SVM        RCKmer-7  0.621±0.140
             244   LogisticRegression        Mismatch  0.577±0.073
             456                  SVM  Z_curve_144bit  0.576±0.099
             246   LogisticRegression     Subsequence  0.571±0.095
islandpick   1914                 SVM        RCKmer-7  0.893±0.057
             1874                 SVM          Kmer-6  0.880±0.046
             378         RandomForest   Z_curve_48bit  0.857±0.050
             683         RandomForest         PseEIIP  0.847±0.052
             687         RandomForest            TPCP  0.842±0.052
islandviewer 174                  SVM        RCKmer-7  0.875±0.016
             2499                 SVM          Kmer-7  0.869±0.017
             228         RandomForest     Subsequence  0.838±0.024
             428         RandomForest   Z_curve_48bit  0.821±0.023
             567         RandomForest            TPCP  0.819±0.016
rvm          1483        RandomForest        RCKmer-5  0.806±0.110
             403         RandomForest   Z_curve_48bit  0.791±0.087
             1448        RandomForest          Kmer-5  0.790±0.136
             1203        RandomForest        PCPseTNC  0.773±0.095
             1206        RandomForest        SCPseDNC  0.765±0.096

                    F_beta_0.5     F_beta_2          MCC     Accuracy  \
dataset
benbow       1049  0.923±0.032  0.933±0.024  0.837±0.048  0.919±0.024
             1014  0.900±0.040  0.920±0.024  0.791±0.061  0.897±0.030
             1143  0.875±0.054  0.886±0.036  0.727±0.079  0.864±0.042
             350   0.859±0.057  0.899±0.020  0.717±0.066  0.860±0.036
             1141  0.868±0.049  0.882±0.020  0.714±0.050  0.859±0.028
gicluster    2284  0.619±0.179  0.665±0.137  0.497±0.197  0.760±0.141
             2324  0.624±0.177  0.651±0.151  0.499±0.199  0.768±0.144
             244   0.555±0.118  0.627±0.095  0.418±0.132  0.729±0.112
             456   0.565±0.145  0.614±0.110  0.404±0.184  0.723±0.134
             246   0.536±0.127  0.629±0.096  0.377±0.183  0.705±0.147
islandpick   1914  0.881±0.087  0.909±0.032  0.832±0.087  0.918±0.050
             1874  0.871±0.075  0.892±0.026  0.812±0.074  0.909±0.039
             378   0.842±0.074  0.874±0.030  0.771±0.090  0.890±0.049
             683   0.833±0.083  0.865±0.034  0.761±0.082  0.884±0.045
             687   0.835±0.077  0.853±0.040  0.751±0.089  0.882±0.049
islandviewer 174   0.868±0.028  0.884±0.016  0.748±0.036  0.873±0.019
             2499  0.859±0.024  0.878±0.017  0.733±0.036  0.866±0.019
             228   0.848±0.031  0.829±0.024  0.684±0.050  0.841±0.025
             428   0.804±0.032  0.841±0.029  0.632±0.050  0.814±0.027
             567   0.800±0.024  0.840±0.022  0.626±0.036  0.811±0.019
rvm          1483  0.808±0.099  0.808±0.130  0.630±0.208  0.811±0.105
             403   0.786±0.082  0.800±0.108  0.599±0.164  0.795±0.082
             1448  0.788±0.110  0.797±0.166  0.608±0.220  0.799±0.111
             1203  0.774±0.087  0.775±0.113  0.563±0.175  0.779±0.087
             1206  0.763±0.076  0.771±0.123  0.550±0.168  0.771±0.084

                     Precision       Recall
dataset
benbow       1049  0.921±0.041  0.936±0.030
             1014  0.894±0.051  0.928±0.032
             1143  0.872±0.067  0.891±0.044
             350   0.848±0.070  0.915±0.024
             1141  0.864±0.062  0.889±0.028
gicluster    2284  0.629±0.219  0.717±0.193
             2324  0.648±0.227  0.696±0.204
             244   0.554±0.174  0.683±0.155
             456   0.572±0.202  0.659±0.158
             246   0.525±0.169  0.690±0.137
islandpick   1914  0.874±0.106  0.922±0.037
             1874  0.866±0.095  0.902±0.035
             378   0.833±0.090  0.887±0.027
             683   0.826±0.105  0.880±0.046
             687   0.831±0.095  0.861±0.046
islandviewer 174   0.863±0.038  0.890±0.026
             2499  0.854±0.031  0.885±0.022
             228   0.855±0.038  0.823±0.028
             428   0.793±0.041  0.855±0.040
             567   0.787±0.032  0.855±0.032
rvm          1483  0.811±0.098  0.811±0.147
             403   0.786±0.093  0.808±0.127
             1448  0.790±0.098  0.805±0.189
             1203  0.776±0.090  0.778±0.127
             1206  0.764±0.070  0.777±0.143

In [17]:
top_benbow_pairs = sub_df_stratified_group_top_n[sub_df_stratified_group_top_n['dataset']=='gicluster'][['representation','model']].values
top_benbow_pairs = [pair[0]+'/'+pair[1] for pair in top_benbow_pairs]
top_benbow_pairs

['Kmer-6/SVM',
 'RCKmer-7/SVM',
 'Mismatch/LogisticRegression',
 'Z_curve_144bit/SVM',
 'Subsequence/LogisticRegression',
 'CKSNAP/SVM',
 'SCPseDNC/RandomForest',
 'Moran/RandomForest',
 'Z_curve_48bit/SVM',
 'Geary/NaiveBayes']

In [9]:
final_df[final_df['dataset']=='islandviewer'].groupby('representation').apply(pd.DataFrame.nlargest, n=5, columns=['mean_F1'])[['model','F1','F_beta_0.5','F_beta_2','MCC','Accuracy','Precision','Recall']]

                                model           F1   F_beta_0.5     F_beta_2  \
representation
ASDC           36        RandomForest  0.785±0.030  0.766±0.032  0.806±0.036
               42                 SVM  0.754±0.032  0.755±0.032  0.755±0.043
               12        DecisionTree  0.709±0.025  0.694±0.032  0.724±0.023
               24  LogisticRegression  0.652±0.036  0.657±0.026  0.650±0.061
               30          NaiveBayes  0.646±0.051  0.681±0.036  0.617±0.075
CKSNAP         37        RandomForest  0.810±0.025  0.791±0.030  0.832±0.032
               43                 SVM  0.795±0.025  0.786±0.033  0.806±0.031
               13        DecisionTree  0.728±0.029  0.720±0.030  0.737±0.033
               25  LogisticRegression  0.661±0.047  0.682±0.036  0.646±0.081
               31          NaiveBayes  0.645±0.044  0.677±0.033  0.619±0.062
DAC            72        RandomForest  0.801±0.023  0.787±0.031  0.817±0.023
               84                 SVM  0.742±0.033  0.744±0.034  0.741±0.042
               24        DecisionTree  0.733±0.024  0.720±0.025  0.748±0.026
               48  LogisticRegression  0.713±0.038  0.727±0.044  0.701±0.047
               60          NaiveBayes  0.707±0.025  0.722±0.033  0.694±0.035
DACC           73        RandomForest  0.794±0.032  0.780±0.042  0.810±0.033
               85                 SVM  0.741±0.024  0.745±0.033  0.738±0.038
               25        DecisionTree  0.723±0.020  0.714±0.022  0.734±0.023
               49  LogisticRegression  0.720±0.030  0.736±0.038  0.707±0.045
               61          NaiveBayes  0.691±0.029  0.704±0.032  0.679±0.047
DCC            74        RandomForest  0.791±0.024  0.777±0.033  0.806±0.031
               86                 SVM  0.734±0.026  0.741±0.033  0.728±0.035
               50  LogisticRegression  0.715±0.036  0.733±0.041  0.699±0.047
               26        DecisionTree  0.706±0.028  0.699±0.030  0.713±0.029
               62          NaiveBayes  0.685±0.028  0.699±0.027  0.673±0.045
DPCP           75        RandomForest  0.784±0.022  0.765±0.032  0.805±0.025
               27        DecisionTree  0.716±0.021  0.701±0.026  0.731±0.018
               87                 SVM  0.704±0.039  0.724±0.031  0.686±0.053
               51  LogisticRegression  0.684±0.039  0.682±0.033  0.689±0.063
               63          NaiveBayes  0.645±0.057  0.681±0.038  0.616±0.078
GC             26  LogisticRegression  0.613±0.038  0.621±0.029  0.608±0.064
               32          NaiveBayes  0.611±0.036  0.636±0.021  0.591±0.060
               44                 SVM  0.586±0.030  0.643±0.030  0.539±0.038
               14        DecisionTree  0.564±0.021  0.563±0.013  0.565±0.032
               38        RandomForest  0.564±0.022  0.562±0.018  0.565±0.028
Geary          76        RandomForest  0.793±0.026  0.776±0.035  0.811±0.028
               88                 SVM  0.731±0.023  0.746±0.027  0.719±0.037
               28        DecisionTree  0.729±0.030  0.718±0.033  0.741±0.031
               52  LogisticRegression  0.711±0.031  0.729±0.032  0.695±0.046
               64          NaiveBayes  0.702±0.028  0.720±0.035  0.687±0.043
MMI            42        RandomForest  0.799±0.027  0.782±0.033  0.817±0.031
               49                 SVM  0.777±0.022  0.771±0.025  0.784±0.030
               28  LogisticRegression  0.732±0.026  0.745±0.029  0.721±0.042
               14        DecisionTree  0.724±0.023  0.714±0.025  0.736±0.026
               35          NaiveBayes  0.673±0.046  0.675±0.032  0.674±0.073
Mismatch       39        RandomForest  0.787±0.022  0.818±0.024  0.760±0.032
               27  LogisticRegression  0.752±0.026  0.763±0.027  0.743±0.039
               15        DecisionTree  0.746±0.015  0.742±0.018  0.750±0.018
               45                 SVM  0.725±0.018  0.784±0.020  0.674±0.030
               33          NaiveBayes  0.531±0.024  0.672±0.021  0.439±0.025
Moran          77        RandomForest  0.794±0.024  0.781±0.030  0.808±0.024
               89                 SVM  0.731±0.025  0.746±0.035  0.719±0.034
               29        DecisionTree  0.727±0.028  0.714±0.028  0.741±0.030
               53  LogisticRegression  0.709±0.029  0.729±0.030  0.691±0.041
               65          NaiveBayes  0.701±0.032  0.718±0.033  0.686±0.043
NAC            40        RandomForest  0.640±0.021  0.640±0.021  0.642±0.038
               46                 SVM  0.623±0.059  0.668±0.035  0.588±0.086
               28  LogisticRegression  0.618±0.036  0.623±0.022  0.616±0.062
               34          NaiveBayes  0.607±0.051  0.635±0.035  0.584±0.073
               16        DecisionTree  0.588±0.021  0.584±0.016  0.593±0.030
NMBroto        78        RandomForest  0.799±0.027  0.785±0.037  0.813±0.026
               90                 SVM  0.737±0.032  0.739±0.042  0.736±0.039
               30        DecisionTree  0.736±0.025  0.723±0.027  0.750±0.029
               54  LogisticRegression  0.714±0.030  0.726±0.037  0.703±0.040
               66          NaiveBayes  0.709±0.031  0.720±0.031  0.700±0.052
PCPseDNC       43        RandomForest  0.796±0.021  0.772±0.027  0.821±0.022
               50                 SVM  0.755±0.030  0.756±0.042  0.755±0.030
               15        DecisionTree  0.727±0.022  0.710±0.025  0.744±0.023
               29  LogisticRegression  0.643±0.054  0.647±0.043  0.641±0.075
               36          NaiveBayes  0.639±0.043  0.683±0.029  0.605±0.066
PCPseTNC       44        RandomForest  0.818±0.025  0.799±0.038  0.839±0.026
               51                 SVM  0.776±0.023  0.775±0.037  0.777±0.022
               16        DecisionTree  0.737±0.031  0.724±0.035  0.750±0.029
               30  LogisticRegression  0.644±0.045  0.645±0.023  0.647±0.079
               37          NaiveBayes  0.641±0.053  0.668±0.037  0.621±0.080
PseDNC         45        RandomForest  0.794±0.026  0.772±0.041  0.818±0.022
               52                 SVM  0.751±0.034  0.751±0.038  0.753±0.043
               17        DecisionTree  0.726±0.026  0.713±0.026  0.741±0.030
               31  LogisticRegression  0.642±0.041  0.646±0.032  0.641±0.063
               38          NaiveBayes  0.641±0.040  0.683±0.042  0.607±0.052
PseEIIP        79        RandomForest  0.817±0.028  0.798±0.041  0.839±0.026
               91                 SVM  0.808±0.029  0.808±0.045  0.810±0.033
               31        DecisionTree  0.740±0.023  0.729±0.028  0.751±0.023
               67          NaiveBayes  0.638±0.061  0.672±0.041  0.611±0.088
               55  LogisticRegression  0.630±0.035  0.642±0.029  0.622±0.060
PseKNC         46        RandomForest  0.817±0.022  0.797±0.033  0.839±0.022
               53                 SVM  0.776±0.022  0.777±0.028  0.775±0.028
               18        DecisionTree  0.736±0.023  0.722±0.028  0.750±0.021
               32  LogisticRegression  0.649±0.041  0.659±0.029  0.643±0.064
               39          NaiveBayes  0.644±0.045  0.678±0.032  0.615±0.070
RCKmer-1       28  LogisticRegression  0.607±0.067  0.617±0.024  0.605±0.107
               35          NaiveBayes  0.607±0.053  0.633±0.023  0.589±0.085
               49                 SVM  0.586±0.037  0.646±0.028  0.538±0.052
               42        RandomForest  0.565±0.024  0.562±0.017  0.568±0.033
               14        DecisionTree  0.562±0.021  0.560±0.015  0.563±0.029
RCKmer-2       43        RandomForest  0.788±0.017  0.758±0.026  0.822±0.015
               15        DecisionTree  0.739±0.022  0.717±0.026  0.762±0.026
               50                 SVM  0.737±0.031  0.741±0.039  0.733±0.037
               29  LogisticRegression  0.662±0.036  0.668±0.044  0.659±0.053
               36          NaiveBayes  0.652±0.039  0.680±0.034  0.627±0.053
RCKmer-3       44        RandomForest  0.820±0.025  0.795±0.035  0.849±0.026
               51                 SVM  0.798±0.031  0.799±0.045  0.799±0.033
               16        DecisionTree  0.752±0.022  0.732±0.028  0.773±0.021
               30  LogisticRegression  0.666±0.049  0.678±0.041  0.657±0.071
               37          NaiveBayes  0.643±0.050  0.670±0.028  0.622±0.080
RCKmer-4       45        RandomForest  0.829±0.024  0.806±0.036  0.854±0.018
               52                 SVM  0.814±0.028  0.815±0.032  0.813±0.033
               17        DecisionTree  0.749±0.026  0.736±0.028  0.763±0.028
               38          NaiveBayes  0.662±0.049  0.691±0.042  0.638±0.067
               31  LogisticRegression  0.655±0.055  0.668±0.032  0.647±0.088
RCKmer-5       53                 SVM  0.838±0.021  0.834±0.028  0.841±0.020
               46        RandomForest  0.837±0.024  0.819±0.038  0.856±0.019
               18        DecisionTree  0.737±0.023  0.725±0.029  0.749±0.022
               39          NaiveBayes  0.663±0.053  0.701±0.043  0.633±0.073
               32  LogisticRegression  0.646±0.041  0.652±0.029  0.643±0.068
RCKmer-6       54                 SVM  0.865±0.019  0.859±0.026  0.871±0.023
               47        RandomForest  0.832±0.025  0.811±0.033  0.855±0.029
               19        DecisionTree  0.712±0.025  0.707±0.029  0.717±0.024
               40          NaiveBayes  0.666±0.050  0.704±0.044  0.635±0.067
               33  LogisticRegression  0.649±0.045  0.657±0.031  0.645±0.076
RCKmer-7       55                 SVM  0.875±0.016  0.868±0.028  0.884±0.016
               48        RandomForest  0.826±0.026  0.809±0.033  0.844±0.034
               20        DecisionTree  0.696±0.019  0.694±0.024  0.699±0.018
               41          NaiveBayes  0.685±0.032  0.720±0.023  0.656±0.052
               34  LogisticRegression  0.655±0.038  0.660±0.026  0.651±0.061
SCPseDNC       47        RandomForest  0.806±0.020  0.786±0.030  0.827±0.016
               19        DecisionTree  0.738±0.024  0.723±0.025  0.753±0.027
               54                 SVM  0.728±0.032  0.742±0.034  0.717±0.039
               40          NaiveBayes  0.692±0.039  0.718±0.036  0.671±0.066
               33  LogisticRegression  0.661±0.045  0.665±0.027  0.660±0.072
SCPseTNC       48        RandomForest  0.819±0.028  0.799±0.041  0.840±0.024
               55                 SVM  0.809±0.023  0.808±0.033  0.811±0.031
               20        DecisionTree  0.733±0.027  0.719±0.031  0.747±0.026
               34  LogisticRegression  0.655±0.047  0.663±0.036  0.649±0.067
               41          NaiveBayes  0.634±0.045  0.673±0.027  0.602±0.067
Subsequence    41        RandomForest  0.838±0.024  0.848±0.031  0.829±0.024
               47                 SVM  0.827±0.019  0.837±0.032  0.818±0.022
               17        DecisionTree  0.774±0.019  0.767±0.023  0.781±0.021
               29  LogisticRegression  0.747±0.036  0.759±0.034  0.736±0.049
               35          NaiveBayes  0.353±0.044  0.500±0.044  0.274±0.040
TAC            80        RandomForest  0.702±0.033  0.697±0.033  0.708±0.040
               92                 SVM  0.643±0.058  0.686±0.048  0.608±0.076
               56  LogisticRegression  0.637±0.054  0.661±0.039  0.618±0.079
               32        DecisionTree  0.636±0.021  0.630±0.019  0.642±0.028
               68          NaiveBayes  0.598±0.045  0.648±0.038  0.559±0.063
TACC           81        RandomForest  0.735±0.024  0.725±0.031  0.746±0.039
               93                 SVM  0.712±0.028  0.729±0.026  0.697±0.043
               57  LogisticRegression  0.652±0.051  0.678±0.036  0.632±0.075
               33        DecisionTree  0.651±0.021  0.647±0.022  0.656±0.021
               69          NaiveBayes  0.600±0.053  0.655±0.035  0.557±0.072
TCC            82        RandomForest  0.688±0.017  0.682±0.017  0.695±0.028
               94                 SVM  0.631±0.030  0.673±0.030  0.597±0.045
               34        DecisionTree  0.614±0.020  0.608±0.017  0.620±0.028
               58  LogisticRegression  0.597±0.055  0.615±0.034  0.584±0.081
               70          NaiveBayes  0.574±0.046  0.635±0.027  0.526±0.066
TPCP           83        RandomForest  0.819±0.016  0.800±0.024  0.840±0.022
               95                 SVM  0.764±0.034  0.762±0.045  0.767±0.039
               35        DecisionTree  0.728±0.027  0.719±0.028  0.737±0.031
               59  LogisticRegression  0.708±0.039  0.711±0.043  0.708±0.054
               71          NaiveBayes  0.637±0.054  0.673±0.038  0.607±0.074
Z_curve_12bit  30        RandomForest  0.790±0.035  0.768±0.048  0.814±0.029
               35                 SVM  0.759±0.025  0.764±0.033  0.756±0.038
               10        DecisionTree  0.719±0.024  0.708±0.027  0.730±0.027
               20  LogisticRegression  0.689±0.042  0.688±0.030  0.693±0.063
               25          NaiveBayes  0.669±0.047  0.687±0.038  0.654±0.063
Z_curve_144bit 36                 SVM  0.814±0.026  0.813±0.038  0.816±0.028
               31        RandomForest  0.786±0.037  0.778±0.058  0.796±0.034
               11        DecisionTree  0.683±0.019  0.678±0.021  0.689±0.020
               21  LogisticRegression  0.667±0.034  0.679±0.024  0.657±0.058
               26          NaiveBayes  0.656±0.050  0.686±0.043  0.630±0.067
Z_curve_36bit  37                 SVM  0.765±0.029  0.768±0.029  0.763±0.039
               32        RandomForest  0.760±0.026  0.758±0.037  0.765±0.032
               12        DecisionTree  0.665±0.030  0.660±0.032  0.670±0.031
               22  LogisticRegression  0.662±0.043  0.665±0.036  0.663±0.070
               27          NaiveBayes  0.659±0.066  0.680±0.042  0.643±0.090
Z_curve_48bit  33        RandomForest  0.821±0.023  0.804±0.032  0.841±0.029
               38                 SVM  0.815±0.024  0.814±0.027  0.817±0.025
               13        DecisionTree  0.728±0.028  0.717±0.029  0.740±0.031
               23  LogisticRegression  0.689±0.035  0.700±0.036  0.682±0.054
               28          NaiveBayes  0.666±0.041  0.693±0.038  0.644±0.054
Z_curve_9bit   34        RandomForest  0.663±0.035  0.674±0.028  0.654±0.055
               39                 SVM  0.633±0.049  0.673±0.042  0.599±0.060
               24  LogisticRegression  0.615±0.040  0.622±0.030  0.612±0.065
               29          NaiveBayes  0.615±0.055  0.649±0.035  0.586±0.076
               14        DecisionTree  0.587±0.020  0.585±0.016  0.589±0.026

                           MCC     Accuracy    Precision       Recall
representation
ASDC           36  0.555±0.064  0.776±0.032  0.754±0.036  0.820±0.044
               42  0.512±0.059  0.755±0.030  0.756±0.038  0.756±0.054
               12  0.397±0.061  0.698±0.031  0.685±0.037  0.735±0.025
               24  0.316±0.047  0.656±0.024  0.662±0.039  0.650±0.079
               30  0.358±0.065  0.675±0.033  0.710±0.045  0.601±0.091
CKSNAP         37  0.608±0.054  0.802±0.028  0.778±0.038  0.847±0.042
               43  0.584±0.056  0.791±0.029  0.781±0.043  0.813±0.041
               13  0.446±0.060  0.723±0.030  0.714±0.032  0.743±0.037
               25  0.362±0.061  0.677±0.031  0.701±0.059  0.640±0.106
               31  0.349±0.058  0.671±0.030  0.701±0.040  0.604±0.075
DAC            72  0.592±0.052  0.794±0.027  0.777±0.038  0.828±0.029
               84  0.488±0.063  0.743±0.031  0.746±0.040  0.741±0.051
               24  0.451±0.050  0.725±0.025  0.711±0.028  0.758±0.031
               48  0.445±0.080  0.721±0.040  0.738±0.054  0.694±0.059
               60  0.434±0.056  0.716±0.028  0.733±0.046  0.686±0.046
DACC           73  0.577±0.075  0.787±0.039  0.771±0.051  0.822±0.042
               85  0.488±0.052  0.742±0.026  0.749±0.047  0.738±0.053
               25  0.435±0.044  0.717±0.022  0.707±0.025  0.741±0.027
               49  0.463±0.062  0.729±0.030  0.749±0.055  0.700±0.060
               61  0.403±0.054  0.700±0.026  0.715±0.047  0.673±0.062
DCC            74  0.571±0.054  0.784±0.028  0.769±0.043  0.817±0.043
               86  0.477±0.055  0.737±0.027  0.747±0.044  0.725±0.046
               50  0.455±0.071  0.726±0.035  0.748±0.055  0.689±0.058
               26  0.402±0.059  0.701±0.030  0.694±0.032  0.719±0.032
               62  0.393±0.047  0.695±0.023  0.710±0.041  0.666±0.057
DPCP           75  0.552±0.053  0.774±0.028  0.753±0.040  0.821±0.033
               27  0.411±0.051  0.705±0.026  0.692±0.031  0.742±0.020
               87  0.439±0.060  0.718±0.030  0.739±0.034  0.676±0.062
               51  0.368±0.063  0.682±0.032  0.682±0.044  0.694±0.083
               63  0.359±0.066  0.676±0.034  0.710±0.039  0.599±0.091
GC             26  0.244±0.061  0.620±0.031  0.629±0.044  0.607±0.084
               32  0.274±0.040  0.635±0.019  0.656±0.041  0.580±0.074
               44  0.289±0.051  0.639±0.024  0.689±0.043  0.513±0.044
               14  0.127±0.024  0.563±0.012  0.563±0.011  0.566±0.039
               38  0.125±0.035  0.562±0.017  0.561±0.017  0.567±0.033
Geary          76  0.572±0.060  0.784±0.031  0.766±0.044  0.825±0.037
               88  0.482±0.043  0.740±0.021  0.757±0.040  0.711±0.048
               28  0.444±0.066  0.721±0.033  0.710±0.036  0.750±0.033
               52  0.448±0.057  0.722±0.029  0.743±0.044  0.686±0.058
               64  0.431±0.059  0.713±0.028  0.734±0.053  0.679±0.055
MMI            42  0.586±0.058  0.791±0.029  0.772±0.040  0.830±0.039
               49  0.549±0.045  0.774±0.023  0.767±0.031  0.789±0.038
               28  0.482±0.048  0.739±0.025  0.756±0.043  0.714±0.055
               14  0.436±0.049  0.717±0.025  0.707±0.029  0.744±0.030
               35  0.355±0.064  0.675±0.033  0.678±0.040  0.677±0.095
Mismatch       39  0.605±0.038  0.800±0.019  0.840±0.035  0.743±0.040
               27  0.518±0.046  0.758±0.023  0.771±0.036  0.737±0.049
               15  0.487±0.033  0.743±0.016  0.739±0.023  0.753±0.023
               45  0.526±0.029  0.756±0.013  0.831±0.036  0.645±0.038
               33  0.358±0.026  0.653±0.013  0.819±0.023  0.393±0.025
Moran          77  0.578±0.054  0.788±0.028  0.773±0.035  0.818±0.029
               89  0.481±0.058  0.739±0.028  0.756±0.049  0.712±0.045
               29  0.438±0.058  0.718±0.029  0.705±0.030  0.750±0.033
               53  0.446±0.055  0.721±0.027  0.744±0.040  0.680±0.051
               65  0.427±0.060  0.712±0.030  0.731±0.042  0.677±0.053
NAC            40  0.281±0.043  0.640±0.022  0.641±0.032  0.644±0.051
               46  0.336±0.061  0.663±0.032  0.705±0.044  0.568±0.101
               28  0.250±0.044  0.623±0.022  0.628±0.032  0.617±0.082
               34  0.276±0.063  0.635±0.031  0.658±0.040  0.571±0.087
               16  0.169±0.031  0.584±0.016  0.582±0.015  0.596±0.037
NMBroto        78  0.587±0.062  0.792±0.032  0.777±0.046  0.824±0.033
               90  0.477±0.071  0.737±0.036  0.741±0.053  0.737±0.051
               30  0.457±0.053  0.728±0.027  0.714±0.032  0.760±0.034
               54  0.445±0.065  0.721±0.032  0.736±0.051  0.697±0.051
               66  0.436±0.052  0.716±0.026  0.730±0.048  0.696±0.068
PCPseDNC       43  0.573±0.047  0.785±0.024  0.758±0.032  0.839±0.028
               50  0.510±0.069  0.754±0.035  0.757±0.053  0.755±0.037
               15  0.434±0.049  0.716±0.025  0.700±0.028  0.756±0.026
               29  0.299±0.079  0.648±0.039  0.652±0.048  0.641±0.092
               36  0.359±0.050  0.674±0.025  0.720±0.055  0.585±0.080
PCPseTNC       44  0.625±0.058  0.810±0.030  0.788±0.050  0.855±0.037
               51  0.551±0.058  0.774±0.029  0.775±0.048  0.779±0.030
               16  0.458±0.068  0.728±0.034  0.716±0.039  0.759±0.030
               30  0.297±0.044  0.646±0.023  0.649±0.037  0.651±0.102
               37  0.335±0.068  0.664±0.034  0.690±0.053  0.610±0.098
PseDNC         45  0.570±0.066  0.782±0.035  0.759±0.052  0.836±0.030
               52  0.504±0.070  0.751±0.036  0.751±0.046  0.755±0.054
               17  0.436±0.053  0.717±0.026  0.704±0.028  0.751±0.035
               31  0.295±0.063  0.646±0.031  0.650±0.042  0.642±0.080